---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:14.13
    commands:
      - npm install
      - npm test

  - name: publish
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: dev