---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:14.13
    commands:
      - npm install
      - npm test

  - name: code-analysis
    image: mailbyms/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
    when:
      branch:
        - master

  - name: publish-version
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: PRODUCTION
      tags:
        - ${DRONE_TAG##v}
    when:
      ref:
        - refs/tags/v*.*.*

  - name: publish-master
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: PRODUCTION
      tags:
        - latest
        - commit-${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - master

  - name: publish-development
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: DEV
      tags:
        - development
        - commit-${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - development
