---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:14.13
    commands:
      - npm install
      - npm test

  - name: code-analysis
    image: mailbyms/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
    when:
      branch:
        - master

  - name: publish-master
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: PRODUCTION_IMAGE
      tags:
        - latest
        - commit-${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - master

  - name: publish-design
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: DEBUG_IMAGE
      tags:
        - dev-design
        - commit-${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - design

  - name: publish-movement
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: DEBUG_IMAGE
      tags:
        - dev-movement
        - commit-${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - movement

  - name: publish-video
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: DEBUG_IMAGE
      tags:
       - dev-video
       - commit-${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - video