---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:14.13
    commands:
      - npm install
      - npm test

  - name: publish-master
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
    when:
      branch:
        - master

  - name: publish-video
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.dev
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: dev-video
    when:
      branch:
        - video

  - name: publish-movement
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.dev
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: dev-movement
    when:
      branch:
        - movement