test-job:
  stage: test
  image: node:14.13
  script:
    - npm install
    - npm test

build-job:
  stage: build
  image: docker:19.03.12
  script:
    - docker build -t test/officemania:test .
    - docker run --rm test/officemania:test npm test